import { useContactForm } from './useContactForm'
import SubmissionPopup from './SubmissionPopup'
import { ArrowRight, CheckCircle2 } from 'lucide-react'
import { assets } from './assets'

import { courses } from './courses'

export function ApplyNowPage() {
  const { submit, status, feedback, popupOpen, dismissPopup } = useContactForm()
  return <main className="apply-page"><SubmissionPopup open={popupOpen} success={status === 'success'} message={feedback} onDismiss={dismissPopup} /><section className="page-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(5,12,10,.72),rgba(5,12,10,.5)),url(${assets.admissions.hero})`}}><div><h1>Apply Now</h1><p>Begin your Oxford journey with one simple step.</p></div></section><section className="apply-intro section-shell section-pad"><div><p className="eyebrow">Start Your Journey</p><h2>Your future begins with a conversation.</h2></div><p>Complete the form and our admissions team will contact you with course details, eligibility guidance and the next steps.</p></section><section className="apply-layout section-shell"><form className="apply-form" onSubmit={submit}><div className="apply-form-heading"><p className="eyebrow">Application Enquiry</p><h2>Tell us about yourself.</h2><p>All fields marked with * are required.</p></div><label>Full Name *<input name="name" minLength={2} maxLength={120} required placeholder="Enter your full name"/></label><label>Email Address *<input name="email" maxLength={254} required type="email" placeholder="Enter your email address"/></label><label>Phone Number *<input name="phone" maxLength={25} required type="tel" placeholder="Enter your phone number"/></label><label>Admissions seeking for *<select name="course" required defaultValue=""><option value="" disabled>Select a course</option>{courses.map(course=><option key={course}>{course}</option>)}</select></label><label className="apply-full">Message<textarea name="message" maxLength={5000} placeholder="Tell us how we can help" rows={4}/></label><button disabled={status === 'sending'} className="apply-submit" type="submit">{status === 'sending' ? 'Sending...' : status === 'success' ?'Enquiry Submitted':'Submit Enquiry'} <ArrowRight size={17}/></button>{feedback&&<p className="form-feedback" role={status === 'error' ? 'alert' : 'status'}>{status === 'success' && <CheckCircle2 size={17}/>} {feedback}</p>}</form><aside className="apply-aside"><p className="eyebrow">Why Oxford</p><h2>Make your next chapter count.</h2><ul><li>Industry-relevant academic programmes</li><li>Supportive faculty and student community</li><li>Practical learning and career guidance</li><li>A campus built for growth and opportunity</li></ul><div className="apply-aside-note"><strong>Need help?</strong><span>Call +91 80 4567 8900 or email admissions@oxford.edu.in</span></div></aside></section></main>
}
